# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='countryPopulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_count', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'country_population',
            },
        ),
    ]
