# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_auto_20180930_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citypopulation',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
