# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0003_auto_20180930_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citypopulation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
