# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0004_auto_20180930_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citypopulation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
